# Generated by Django 3.1.4 on 2020-12-19 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athleteuser',
            old_name='clients',
            new_name='trainer',
        ),
    ]
