# Generated by Django 3.1.4 on 2021-02-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210206_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteuser',
            name='aomunt_excersise',
            field=models.CharField(choices=[('Poco o ningún ejericio', 'NE'), ('Ejercicio ligero (1-3 días a la semana)', 'EL'), ('Ejercicio moderado (3-5 días a la semana)', 'EM'), ('Ejercicio fuerte (6-7 días a la semana)', 'EF'), ('Ejercicio muy fuerto (dos veces al día entrenamientos muy duros)', 'EMF')], default='EM', help_text='Choices of sport activity ', max_length=80, verbose_name='amount_excersise'),
        ),
    ]
