# Generated by Django 3.1.4 on 2021-02-10 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_athleteuser_aomunt_excersise'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='Modified at')),
                ('user_count', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='athleteuser',
            name='aomunt_excersise',
        ),
        migrations.AddField(
            model_name='athleteuser',
            name='amount_excersise',
            field=models.CharField(choices=[('ne', 'NE'), ('el', 'EL'), ('em', 'EM'), ('ef', 'EF'), ('emf', 'EMF')], default='NE', help_text='Choices of sport activity ', max_length=80, verbose_name='amount_excersise'),
        ),
        migrations.AlterField(
            model_name='invitationcode',
            name='key',
            field=models.CharField(blank=True, max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='key'),
        ),
        migrations.AddField(
            model_name='traineruser',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_plans', to='users.trainerplan'),
        ),
    ]
