# Generated by Django 3.1.4 on 2021-02-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_athleteuser_aomunt_excersise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athleteuser',
            name='aomunt_excersise',
        ),
        migrations.AddField(
            model_name='athleteuser',
            name='amount_excersise',
            field=models.CharField(choices=[('ne', 'NE'), ('el', 'EL'), ('em', 'EM'), ('ef', 'EF'), ('emf', 'EMF')], default='NE', help_text='Choices of sport activity ', max_length=80, verbose_name='amount_excersise'),
        ),
    ]
