# Generated by Django 3.1.4 on 2021-02-10 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210210_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traineruser',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_plan', to='users.trainerplan'),
        ),
    ]
