# Generated by Django 3.1.4 on 2021-02-10 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210210_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traineruser',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_plan', to='users.trainerplan'),
        ),
    ]
