# Generated by Django 3.1.4 on 2021-02-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_expopushtoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expopushtoken',
            options={},
        ),
        migrations.AlterField(
            model_name='expopushtoken',
            name='token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='expopushtoken',
            unique_together={('user', 'token')},
        ),
    ]
