# Generated by Django 3.1.6 on 2021-02-16 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0009_auto_20210205_1930'),
        ('users', '0014_auto_20210215_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteuser',
            name='diet',
            field=models.OneToOneField(blank=True, help_text='Diet of the user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_diet', to='trainings.diet'),
        ),
        migrations.AlterField(
            model_name='athleteuser',
            name='rutine',
            field=models.OneToOneField(blank=True, help_text='Rutine of the user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_rutine', to='trainings.rutine'),
        ),
    ]
