# Generated by Django 3.1.7 on 2021-03-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210228_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athleteuser',
            name='alergias',
        ),
        migrations.AddField(
            model_name='athleteuser',
            name='alergias',
            field=models.TextField(blank=True, null=True),
        ),
    ]
