# Generated by Django 3.1.7 on 2021-03-31 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='message',
            name='to',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
