# Generated by Django 3.1.4 on 2021-01-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalhistory',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
