# Generated by Django 3.1.4 on 2021-01-02 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('history', '0002_auto_20210102_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='Modified at')),
                ('date', models.DateField(verbose_name='Date of the publication')),
                ('history_type', models.CharField(choices=[('WEIGHT', 'weight'), ('HEIGHT', 'height'), ('FAT', 'fat')], max_length=100, verbose_name='Type of history behaviour')),
                ('data', models.FloatField(verbose_name='data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='sporthistory',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name of the sport'),
        ),
        migrations.DeleteModel(
            name='MeasurementSportsHistory',
        ),
    ]
