# Generated by Django 3.1.4 on 2021-01-10 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20210109_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalhistory',
            options={'ordering': ('-date', '-created')},
        ),
    ]
