# Generated by Django 3.1.4 on 2021-02-08 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_auto_20210110_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weighthistory',
            options={'get_latest_by': ['-created'], 'ordering': ('-created',)},
        ),
    ]
