# Generated by Django 3.1.4 on 2020-12-19 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('anotation', models.TextField(blank=True, null=True)),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.athleteuser')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.traineruser')),
            ],
        ),
        migrations.CreateModel(
            name='DietDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
                ('anotation', models.TextField(blank=True, null=True)),
                ('rutine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.diet')),
            ],
        ),
        migrations.CreateModel(
            name='DietGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('anotation', models.TextField(blank=True, null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.dietday')),
            ],
        ),
        migrations.CreateModel(
            name='DietRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('preparation', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.dietgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Excersise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('difficult', models.IntegerField(choices=[(1, 'Very easy'), (2, 'easy'), (3, 'Medium'), (4, 'Difficult'), (5, 'Hardcore')])),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('protein', models.IntegerField()),
                ('carbohydrates', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('kcalories', models.IntegerField()),
                ('portion_weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rutine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.athleteuser')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.traineruser')),
            ],
        ),
        migrations.CreateModel(
            name='RutineDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
                ('rutine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='trainings.rutine')),
            ],
        ),
        migrations.CreateModel(
            name='RutineGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='trainings.rutineday')),
            ],
        ),
        migrations.CreateModel(
            name='RutineExcersise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=400)),
                ('anotation', models.TextField()),
                ('order', models.IntegerField()),
                ('excersise', models.ManyToManyField(to='trainings.Excersise')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excersises', to='trainings.rutinegroup')),
            ],
        ),
        migrations.CreateModel(
            name='DietRecipeFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portion_cuantity', models.IntegerField()),
                ('portion_unity', models.IntegerField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.food')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.dietgroup')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.dietrecipe')),
            ],
        ),
        migrations.CreateModel(
            name='DietFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portion_cuantity', models.IntegerField()),
                ('portion_unity', models.IntegerField(choices=[(0, 'gr'), (1, 'oz'), (2, 'unity')])),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.food')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.dietgroup')),
            ],
        ),
    ]
