# Generated by Django 3.1.4 on 2020-12-22 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainings', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutine',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.traineruser'),
        ),
        migrations.AddField(
            model_name='dietrecipefood',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.food'),
        ),
        migrations.AddField(
            model_name='dietrecipefood',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.dietgroup'),
        ),
        migrations.AddField(
            model_name='dietrecipefood',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.dietrecipe'),
        ),
        migrations.AddField(
            model_name='dietrecipe',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.dietgroup'),
        ),
        migrations.AddField(
            model_name='dietgroup',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.dietday'),
        ),
        migrations.AddField(
            model_name='dietfood',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.food'),
        ),
        migrations.AddField(
            model_name='dietfood',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.dietgroup'),
        ),
        migrations.AddField(
            model_name='dietday',
            name='rutine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.diet'),
        ),
        migrations.AddField(
            model_name='diet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.traineruser'),
        ),
    ]
