# Generated by Django 3.1.4 on 2020-12-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_auto_20201226_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietrecipefood',
            name='portion_unity',
            field=models.CharField(choices=[('gr', 'gramos'), ('oz', 'oz'), ('unity', 'unity')], default=0, max_length=14),
        ),
    ]
