# Generated by Django 3.1.4 on 2020-12-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0004_auto_20201226_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='excersise',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
