# Generated by Django 3.1.4 on 2021-01-02 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0005_excersise_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diet',
            options={'get_latest_by': 'created', 'ordering': ['-created', '-modified']},
        ),
        migrations.AlterModelOptions(
            name='dietday',
            options={'get_latest_by': 'created', 'ordering': ['-created', '-modified']},
        ),
        migrations.AlterModelOptions(
            name='dietfood',
            options={'get_latest_by': 'created', 'ordering': ['-created', '-modified']},
        ),
        migrations.AlterModelOptions(
            name='dietgroup',
            options={'get_latest_by': 'created', 'ordering': ['-created', '-modified']},
        ),
        migrations.AlterModelOptions(
            name='dietrecipe',
            options={'get_latest_by': 'created', 'ordering': ['-created', '-modified']},
        ),
        migrations.AlterModelOptions(
            name='dietrecipefood',
            options={'get_latest_by': 'created', 'ordering': ['-created', '-modified']},
        ),
        migrations.AlterModelOptions(
            name='excersise',
            options={'get_latest_by': 'created', 'ordering': ['-created', '-modified']},
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'get_latest_by': 'created', 'ordering': ['-created', '-modified']},
        ),
        migrations.AlterModelOptions(
            name='rutine',
            options={'get_latest_by': 'created', 'ordering': ['-created', '-modified']},
        ),
        migrations.AlterModelOptions(
            name='rutineday',
            options={'get_latest_by': 'created', 'ordering': ['-created', '-modified']},
        ),
        migrations.AlterModelOptions(
            name='rutineexcersise',
            options={'get_latest_by': 'created', 'ordering': ['-created', '-modified']},
        ),
        migrations.AlterModelOptions(
            name='rutinegroup',
            options={'get_latest_by': 'created', 'ordering': ['-created', '-modified']},
        ),
        migrations.AddField(
            model_name='diet',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date time on which the object was created', verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diet',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='Modified at'),
        ),
        migrations.AddField(
            model_name='dietday',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date time on which the object was created', verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dietday',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='Modified at'),
        ),
        migrations.AddField(
            model_name='dietfood',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date time on which the object was created', verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dietfood',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='Modified at'),
        ),
        migrations.AddField(
            model_name='dietgroup',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date time on which the object was created', verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dietgroup',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='Modified at'),
        ),
        migrations.AddField(
            model_name='dietrecipe',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date time on which the object was created', verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dietrecipe',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='Modified at'),
        ),
        migrations.AddField(
            model_name='dietrecipefood',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date time on which the object was created', verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dietrecipefood',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='Modified at'),
        ),
        migrations.AddField(
            model_name='excersise',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date time on which the object was created', verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='excersise',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='Modified at'),
        ),
        migrations.AddField(
            model_name='food',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date time on which the object was created', verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='Modified at'),
        ),
        migrations.AddField(
            model_name='rutine',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date time on which the object was created', verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rutine',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='Modified at'),
        ),
        migrations.AddField(
            model_name='rutineday',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date time on which the object was created', verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rutineday',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='Modified at'),
        ),
        migrations.AddField(
            model_name='rutineexcersise',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date time on which the object was created', verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rutineexcersise',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='Modified at'),
        ),
        migrations.AddField(
            model_name='rutinegroup',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date time on which the object was created', verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rutinegroup',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='Modified at'),
        ),
    ]
