# Generated by Django 3.1.4 on 2021-02-04 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0006_auto_20210102_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rutineday',
            options={'get_latest_by': ['-order'], 'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='rutineexcersise',
            options={'get_latest_by': ['-order'], 'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='rutinegroup',
            options={'get_latest_by': ['-order'], 'ordering': ('order',)},
        ),
        migrations.AlterField(
            model_name='dietday',
            name='anotation',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='dietday',
            name='order',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='rutineday',
            name='name',
            field=models.CharField(default='Día nuevo', max_length=255),
        ),
        migrations.AlterField(
            model_name='rutineday',
            name='order',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='rutineexcersise',
            name='order',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='rutinegroup',
            name='name',
            field=models.CharField(default='Grupo nuevo', max_length=255),
        ),
        migrations.AlterField(
            model_name='rutinegroup',
            name='order',
            field=models.BigIntegerField(blank=True),
        ),
    ]
