# Generated by Django 3.1.4 on 2021-02-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0007_auto_20210204_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutineday',
            name='order',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rutineexcersise',
            name='order',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rutinegroup',
            name='order',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
