# Generated by Django 3.1.4 on 2021-02-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0008_auto_20210204_0204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dietday',
            options={'get_latest_by': ['-order'], 'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='dietfood',
            options={'get_latest_by': ['-order'], 'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='dietgroup',
            options={'get_latest_by': ['-order'], 'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='dietrecipe',
            options={'get_latest_by': ['-order'], 'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='dietfood',
            name='order',
            field=models.BigIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dietgroup',
            name='order',
            field=models.BigIntegerField(blank=True, default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dietrecipe',
            name='order',
            field=models.BigIntegerField(blank=True, default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rutineday',
            name='order',
            field=models.BigIntegerField(blank=True, default=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rutineexcersise',
            name='order',
            field=models.BigIntegerField(blank=True, default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rutinegroup',
            name='order',
            field=models.BigIntegerField(blank=True, default=6),
            preserve_default=False,
        ),
    ]
