# Generated by Django 3.1.7 on 2021-02-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0009_auto_20210205_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='carbohydrates',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='kcalories',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='portion_weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.FloatField(),
        ),
    ]
