# Generated by Django 3.1.7 on 2021-03-25 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210303_1537'),
        ('trainings', '0011_food_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='owner',
            field=models.ForeignKey(blank=True, db_column='trainer_owner', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.traineruser'),
        ),
    ]
