# Generated by Django 3.1.7 on 2021-03-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0014_auto_20210325_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excersise',
            name='public',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='public',
            field=models.BooleanField(blank=True, db_column='is_public', default=False),
        ),
    ]
