# Generated by Django 3.1.7 on 2021-03-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0015_auto_20210326_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excersise',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
