# Generated by Django 3.1.7 on 2021-03-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0016_auto_20210326_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='excersisetag',
            name='color_primary',
            field=models.CharField(default='#ffc600', max_length=244),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='excersisetag',
            name='color_secondary',
            field=models.CharField(default='#ffc600', max_length=244),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodtag',
            name='color_primary',
            field=models.CharField(default='ffc600', max_length=244),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodtag',
            name='color_secondary',
            field=models.CharField(default='#ffc600', max_length=244),
            preserve_default=False,
        ),
    ]
