# Generated by Django 3.1.7 on 2021-03-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0018_auto_20210328_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excersisetag',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='foodtag',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
