# Generated by Django 3.1.7 on 2021-03-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210303_1537'),
        ('trainings', '0019_auto_20210328_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='excersise',
            name='favourites',
            field=models.ManyToManyField(related_name='excersise_favourites', to='users.TrainerUser'),
        ),
        migrations.AddField(
            model_name='food',
            name='favourites',
            field=models.ManyToManyField(related_name='diet_favourites', to='users.TrainerUser'),
        ),
    ]
