# Generated by Django 3.1.7 on 2021-03-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210303_1537'),
        ('trainings', '0021_auto_20210328_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='diet_favourites', to='users.TrainerUser'),
        ),
        migrations.AlterField(
            model_name='food',
            name='public',
            field=models.BooleanField(blank=True, db_column='public', default=False),
        ),
    ]
