# Generated by Django 3.2 on 2021-05-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0022_auto_20210329_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='excersisetag',
            name='category',
            field=models.CharField(choices=[('TI', 'Tipo'), ('MU', 'Músculos'), ('EQ', 'Equipamiento')], default='TI', max_length=100),
        ),
    ]
