# Generated by Django 3.2 on 2021-05-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0023_excersisetag_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtag',
            name='category',
            field=models.CharField(choices=[('TI', 'Tipo'), ('AL', 'Alérgenos')], default='TI', max_length=100),
        ),
    ]
